import type { MetadataRoute } from 'next';
import { SITE } from '@/lib/site';

/**
 * Web app manifest.
 *
 * Icons are generated by `scripts/make-icons.mjs` from the same monogram
 * geometry as the on-page wordmark (EFFECT-08): a seedling leaf in
 * --accent-color (#116530).
 *
 * The 512px icon is flagged `maskable` because it is drawn with the mark
 * pulled into the inner safe area — Android can crop it to a circle, squircle
 * or rounded square without clipping the leaf. The 32px favicon is
 * deliberately NOT listed here: at that size a maskable crop would eat the
 * mark, and the tab icon is already declared in layout.tsx.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE.name,
    short_name: SITE.shortName,
    description: SITE.description,
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#ffffff',
    theme_color: '#116530',
    // BCP-47. SITE.locale is the OG format (`en_KE`); the manifest needs a
    // hyphen, and we tag it Kenyan English rather than plain `en` because
    // prices are KES and delivery zones are Nairobi-specific.
    lang: 'en-KE',
    categories: ['food', 'shopping', 'business'],
    icons: [
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    shortcuts: [
      { name: 'Place a bulk order', short_name: 'Order', url: '/order' },
      { name: 'Browse produce', short_name: 'Produce', url: '/produce' },
      { name: 'Become a farm partner', short_name: 'Partner', url: '/partnership' },
    ],
  };
}
